[project]
name = "uptime-kuma-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["dotenv>=0.9.9", "mcp[cli]>=1.6.0", "uptime-kuma-api>=1.2.1"]
